name: app-build-action

on:

  workflow_dispatch:

    inputs:

      shell:

        description: 'shell'

        required: true

        default: 'ls'

jobs:

  # MACOS 镜像

  build-mac-ios-android:

    runs-on: macos-latest

    permissions:

      contents: write

    steps:

      # 1.1 签出代码

      - uses: actions/checkout@v3

        with:

          ref: main

      # 1.2 设置JAVA环境

      - name: Setup JAVA

        uses: actions/setup-java@v3

        with:

          distribution: "zulu"

          java-version: "12.x"

          cache: "gradle"

      # 1.3 设置Flutter环境

      - name: Setup Flutter

        uses: subosito/flutter-action@v2

        with:

          flutter-version: "3.7.7"

          cache: true

      - name: Enable Flutter Desktop

        run: flutter config --enable-macos-desktop

      # 1.4 更新Flutter的packages

      - name: Restore Packages

        run: flutter pub get

      # 1.5 安装appdmg npm install -g appdmg

      - name: Install appdmg

        run: npm install -g appdmg

      # 1.6 设置flutter_distributor环境

      - name: Install flutter_distributor

        run: dart pub global activate flutter_distributor

      # 1.7 build APK

      - name: Build APK

        run: flutter build apk --release


